//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RandLottery.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RANDLOTTERY_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDI_ICON_OPEN                   130
#define IDB_BITMAP_BG1                  132
#define IDD_DIALOG_LIST_SET             134
#define IDR_MENU                        138
#define IDD_DIALOG_TITLE_SET            139
#define IDD_DIALOG_FLOAT                140
#define IDB_BITMAP1                     142
#define IDB_BITMAP_BG2                  143
#define IDB_BITMAP_BG3                  149
#define IDB_BITMAP_BG4                  150
#define IDB_BITMAP2                     151
#define IDD_DIALOG_MUSIC_SET            152
#define IDD_DIALOG_ITEM_SET             153
#define IDB_BITMAP_FLOAT                155
#define IDI_ICON_START                  156
#define IDI_ICON_STOP                   157
#define IDD_DIALOG_RESULT               158
#define IDI_ICON_MYNAME                 162
#define IDC_BUTTON_STOP                 1004
#define IDC_BUTTON_START                1006
#define IDC_EDIT_PATH                   1007
#define IDC_BUTTON_SETTING              1008
#define IDC_LIST_INFO                   1011
#define IDC_BUTTON_OPEN                 1012
#define IDC_LIST_INFO1                  1014
#define IDC_STATIC_TILTE                1015
#define IDC_STATIC_TILTE2               1016
#define IDC_TILTE                       1017
#define IDC_TILTE2                      1018
#define IDC_BUTTON_CORLOR               1019
#define IDC_BUTTON_CORLOR2              1020
#define IDC_ID                          1021
#define IDC_COMBO_FONT_NAME             1022
#define IDC_COMBO_FONT_SIZE             1023
#define IDC_LOGO                        1027
#define IDC_CHECK_BKGROUND              1029
#define IDC_BUTTON_CORLOR_RANK          1029
#define IDC_CHECK_START                 1030
#define IDC_BUTTON_CORLOR_ITEM          1030
#define IDC_CHECK_STOP                  1031
#define IDC_CHECK_RESULT                1032
#define IDC_BUTTON_RANK_SHOW_FONT       1032
#define IDC_STATIC_BKGROUND             1033
#define IDC_BUTTON_TITLE_FONT           1033
#define IDC_STATIC_START                1034
#define IDC_BUTTON_TITLE_FONT2          1034
#define IDC_STATIC_STOP                 1035
#define IDC_BUTTON_ID_FONT              1035
#define IDC_STATIC_RESULT               1036
#define IDC_BUTTON_ITEM_SHOW_FONT       1036
#define IDC_STATIC_BK_OPEN              1037
#define IDC_STATIC_START_OPEN           1038
#define IDC_STATIC_STOP_OPEN            1039
#define IDC_STATIC_RESULT_OPEN          1040
#define IDC_BUTTON_BK_PLAY              1041
#define IDC_BUTTON_START_PLAY           1043
#define IDC_BUTTON_AWORD_PLAY           1044
#define IDC_BUTTON_STOP_PLAY            1045
#define IDC_LIST_ITEM                   1049
#define IDC_STATIC_ITEM                 1050
#define IDC_STATIC_ITEM_OPEN            1051
#define IDC_LIST_ITEM_1                 1052
#define IDC_STATIC_ITEM_RANK            1053
#define IDC_STATIC_ITEM_AMOUNT          1054
#define IDC_STATIC_ITEM_AWORD           1055
#define IDC_STATIC_NOTIC                1056
#define IDC_STATIC_ITEM_SHOW            1057
#define IDC_RADIO_SHOW_NAME             1058
#define IDC_RADIO_SHOW_ID               1059
#define IDC_RADIO_SHOW_TEL              1060
#define IDC_STATIC_SHOW_AWORD           1061
#define IDC_STATIC_SHOW_RESULT2         1062
#define IDC_BUTTON_COLOR_ID             1062
#define IDC_STATIC_SHOW_EMAIL           1063
#define IDC_STATIC_LIST_AMOUNT          1063
#define IDC_LIST_RESULT                 1064
#define IDC_CHECK_CIRCLE_PLAY           1066
#define IDC_BUTTON_SAVE                 1067
#define IDC_SPIN_TITLE_TOP              1069
#define IDC_BUTTON_TITLE_LOCATION       1070
#define IDC_EDIT_TITLE_TOP              1071
#define IDC_SPIN_TITLE_LEFT             1072
#define IDC_EDIT_TITLE_LEFT             1073
#define IDC_SPIN_ID_TOP                 1074
#define IDC_EDIT_ID_TOP                 1075
#define IDC_SPIN_ID_LEFT                1076
#define IDC_EDIT_ID_LEFT                1077
#define IDC_BUTTON_ID_LOCATION          1078
#define IDC_SPIN_TITLE_TOP2             1079
#define IDC_EDIT_TITLE_TOP2             1080
#define IDC_BUTTON_TITLE_LOCATION2      1081
#define IDC_SPIN_TITLE_LEFT2            1082
#define IDC_EDIT_TITLE_LEFT2            1083
#define IDC_CHECK_SHOW_TITLE2           1084
#define IDC_SPIN_RANK_TOP               1085
#define IDC_EDIT_RANK_TOP               1086
#define IDC_BUTTON_RANK_LOCATION        1087
#define IDC_SPIN_RANK_LEFT              1088
#define IDC_EDIT_RANK_LEFT              1089
#define IDC_CHECK_SHOW_RANK             1090
#define IDC_RADIO_L                     1091
#define IDC_RADIO_V                     1092
#define IDC_RADIO_R                     1093
#define IDC_SEPARATOR                   1094
#define IDC_BUTTON_CUT                  1095
#define IDC_SPIN_ITEM_TOP               1096
#define IDC_CHECK_REPEAT                1096
#define IDC_EDIT_ITEM_TOP               1097
#define IDC_CHECK_AUTO_SAVE             1097
#define IDC_BUTTON_ITEM_LOCATION        1098
#define IDC_STATIC_ROLL_TOP_AREA        1098
#define IDC_SPIN_ITEM_LEFT              1099
#define IDC_STATIC_ROLL_BOTTOM_AREA     1099
#define IDC_EDIT_ITEM_LEFT              1100
#define IDC_STATIC_TITLE_AREA           1100
#define IDC_CHECK_SHOW_ITEM             1101
#define IDC_STATIC_RANK_AREA            1101
#define IDC_STATIC_ID_AREA              1102
#define IDC_STATIC_ITEM_AREA            1103
#define IDC_STATIC_NOTIC_AREA           1104
#define IDC_STATIC_BUTTOM_AREA          1105
#define IDC_EDIT_MACHINE_SERIAL         1107
#define IDC_EDIT_REG1                   1108
#define IDC_EDIT_REG2                   1109
#define IDC_EDIT_REG3                   1110
#define IDC_EDIT_REG4                   1111
#define IDC_STATIC_TAOBAO               1113
#define IDC_STATIC_QQ                   1114
#define IDC_COMBO_IDCOUNT               1115
#define IDC_STATIC_EMAIL                1115
#define IDC_BUTTON_BG                   1116
#define IDC_STATIC_ID                   2000
#define IDC_STATIC_ID1                  2001
#define IDC_STATIC_ID2                  2002
#define IDC_STATIC_ID3                  2003
#define IDC_STATIC_ID4                  2004
#define IDC_STATIC_ID5                  2005
#define IDC_STATIC_ID6                  2006
#define IDC_STATIC_ID7                  2007
#define IDC_STATIC_ID8                  2008
#define IDC_STATIC_ID9                  2009
#define ID_MENU_LOTTERY_NAME            32772
#define ID_MENU_MUSIC_SETTING           32774
#define ID_MENU_CANCLE                  32775
#define ID_MENU_START                   32777
#define ID_MENU_ITEMSETTING             32779
#define ID_MENU_ABOUT                   32780
#define ID_MENU_STOP                    32781
#define ID_MENU_TITLESETTING            32782
#define ID_MENU_LOTTERY_LIST            32783
#define ID_MENU_HIDE                    32785
#define IDC_MENU_BG1                    32787
#define IDC_MENU_BG2                    32788
#define IDC_MENU_BG3                    32789
#define IDC_MENU_BG4                    32790
#define ID_MENU_NOLOTTERY_LIST          32791
#define ID_MENU_RESULT                  32792
#define ID_MENU_RESET                   32793
#define ID_MENU_BG_MORE                 32794
#define ID_MENU_CONTINUE                32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
